# Generated by Django 4.2.4 on 2023-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='messages',
            new_name='message',
        ),
    ]
